name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  meta: ^1.3.0
  very_good_analysis: ^2.4.0
  firebase_auth: ^3.3.19
  firebase_core: ^1.18.0
  google_sign_in: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
